// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDufWPBJudyV_JSfy0dKZ1G8m4AI5jReH0',
    appId: '1:1063594069329:web:892597d423f3b24ae51770',
    messagingSenderId: '1063594069329',
    projectId: 'sensorvilleapp',
    authDomain: 'sensorvilleapp.firebaseapp.com',
    storageBucket: 'sensorvilleapp.firebasestorage.app',
    measurementId: 'G-LDBMHZCPSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAG72iUC4mXwAuPAS_sX7BaeCQocDu59E',
    appId: '1:1063594069329:android:8d2dfcd6f7202fcfe51770',
    messagingSenderId: '1063594069329',
    projectId: 'sensorvilleapp',
    storageBucket: 'sensorvilleapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBowUmEOl4QLgxCW4jYyrqA2u9x-J-zkP0',
    appId: '1:1063594069329:ios:45a04ea61d114d36e51770',
    messagingSenderId: '1063594069329',
    projectId: 'sensorvilleapp',
    storageBucket: 'sensorvilleapp.firebasestorage.app',
    iosBundleId: 'com.example.sensorvilleapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBowUmEOl4QLgxCW4jYyrqA2u9x-J-zkP0',
    appId: '1:1063594069329:ios:45a04ea61d114d36e51770',
    messagingSenderId: '1063594069329',
    projectId: 'sensorvilleapp',
    storageBucket: 'sensorvilleapp.firebasestorage.app',
    iosBundleId: 'com.example.sensorvilleapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDufWPBJudyV_JSfy0dKZ1G8m4AI5jReH0',
    appId: '1:1063594069329:web:f519d685470ad165e51770',
    messagingSenderId: '1063594069329',
    projectId: 'sensorvilleapp',
    authDomain: 'sensorvilleapp.firebaseapp.com',
    storageBucket: 'sensorvilleapp.firebasestorage.app',
    measurementId: 'G-SZ596LWZGL',
  );
}
